name: Urban Bistro-Bar
favicon: null
layout_spectrum: 0.75886
typography_spectrum: 0.48695
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b060a'
    - '#7c6859'
    - '#bea287'
    - '#452d2d'
    - '#fbeccc'
  brandStrength: 1
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
