name: Urban Bistro-Bar
favicon: null
layout_spectrum: 0.50176
typography_spectrum: 0.64722
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b060a'
    - '#7c6859'
    - '#bea287'
    - '#452d2d'
    - '#fbeccc'
  brandStrength: 0.1386963464319706
  lightness: 0.6875
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
